// Bilingual content for the Prophetgram landing page

const COPY = {
  en: {
    htmlLang: "en",
    eyebrow: "◐ \u00a0 Coming \u00a0/\u00a0 soon \u00a0—\u00a0 nothing to sign up for yet",
    h1_a: "State",
    h1_b: "your goal.",
    h1_italic_a: "Prophetgram",
    h1_italic_b: "builds",
    h1_c: "the plan.",
    body: "A goal-driven content strategy app for Instagram creators. You upload your data and set a goal — Prophetgram builds a 12-week calendar from forecasts of your own posts, not vibes. Powered by Meta's Prophet prediction engine.",
    fig: "FIG. 01–10",
    figLabel: "user-side wireframes",
    figRight: "cards on the table",
    howItWorks: "How it works",
    steps: [
      "Upload your Business Suite CSV.",
      "Identify and set realistic goals.",
      "Get a 12-week calendar back.",
      "Check in weekly. Free.",
    ],
    nav: { ver: "v0.5 · alpha", date: "est. may 2026", lang: "EN", langOther: "UK" },
    footerCenter: "◯ \u00a0 not yet open",
    wireTitles: {
      Landing: "Landing",
      Language: "Language + account",
      Export: "Export walkthrough",
      Upload: "Upload + coverage",
      Categorize: "Categorize posts",
      Goal: "Set a goal",
      Achievability: "Achievability check",
      Strategy: "Strategy delivered",
      Checkin: "Weekly check-in",
      Credits: "Refresh & pivot",
    },
  },
  uk: {
    htmlLang: "uk",
    eyebrow: "◐ \u00a0 Готуємось \u00a0/\u00a0 ще не зараз \u00a0—\u00a0 без ранніх реєстрацій",
    h1_a: "Скажіть,",
    h1_b: "куди йдемо.",
    h1_italic_a: "Prophetgram",
    h1_italic_b: "прокладе",
    h1_c: "маршрут.",
    body: "Контент-стратегія для Instagram-авторів — від цілі, а не від настрою. Ви вивантажуєте свою статистику й називаєте мету — Prophetgram збирає календар на 12 тижнів із прогнозів за вашими ж постами. Працює на Prophet — рушії прогнозування від Meta.",
    fig: "FIG. 01–10",
    figLabel: "екрани користувача",
    figRight: "усі карти відкриті",
    howItWorks: "Як це влаштовано",
    steps: [
      "Експортуйте CSV із Business Suite.",
      "Сформулюйте мету, до якої справді можна дійти.",
      "Отримайте 12-тижневий календар у відповідь.",
      "Звіряйтесь раз на тиждень. Безкоштовно.",
    ],
    nav: { ver: "v0.5 · альфа", date: "трав. 2026", lang: "UK", langOther: "EN" },
    footerCenter: "◯ \u00a0 двері ще зачинені",
    wireTitles: {
      Landing: "Перший екран",
      Language: "Мова та акаунт",
      Export: "Як вивантажити дані",
      Upload: "Завантаження й покриття",
      Categorize: "Розбір постів",
      Goal: "Формулювання мети",
      Achievability: "Чи реально дійти",
      Strategy: "Стратегія готова",
      Checkin: "Тижневе звіряння",
      Credits: "Оновити курс",
    },
  },
};

window.COPY = COPY;
